### ISSUE TITLE
Always return null

### ISSUE THREAD

**Issue by ChEmO1990** [patrickfav/uber-apk-signer#1]
I´am trying to run any command and always return this:

**source:
null
Run with '-debug' parameter to get additional information.**

**Comment by patrickfav** [comment]
Please add --debug to your command and post the command and result.

**Comment by ChEmO1990** [comment]
I'm sorry. Everything is fine. My mistake!!!

**Comment by alouanemed** [comment]
```
s
$ java -jar signer.jar -a appk.apk --ks akeytool.jks --ksAlias skiralias -                                                                                   debug
source:
null
java.lang.NullPointerException
        at at.favre.tools.apksigner.ui.FileArgParser.lambda$getDirSummary$0(File                                                                                   ArgParser.java:59)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source                                                                                   )
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at at.favre.tools.apksigner.ui.FileArgParser.getDirSummary(FileArgParser                                                                                   .java:63)
        at at.favre.tools.apksigner.SignTool.execute(SignTool.java:64)
        at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:41)
        at at.favre.tools.apksigner.SignTool.main(SignTool.java:29)

Cmd history for debugging purpose:
-----------------------

```

**Comment by patrickfav** [comment]
It's probably _app.apk_ not _appk.apk_?

**Comment by dhruv2601** [comment]
@alouanemed any luck with that error?
