### ISSUE TITLE
Could not execute zipalign

### ISSUE THREAD

**Issue by LeducH** [patrickfav/uber-apk-signer#26]
I wan to sign my apk packages but I get the following error 

```
$ archlinux-java status
Available Java environments:
  java-11-openjdk
  java-8-jdk (default)
  java-8-openjdk

$ java -jar uber-apk-signer-1.2.1.jar....
zipalign location: BUILT_IN 
	/tmp/uapksigner-834599882927137790/linux-zipalign-29_0_2262257386856777324.tmp
keystore:
.................

01. app-release-unsigned.apk

	SIGN
	file: /home/user/..../apk/release/app-release-unsigned.apk (0.17 MiB)
	checksum: 35412b8284d3c5374cec45cd4993c544e26ef4d7b50a9c41aa6e12024a97888 (sha256)
	- could not align 
could not execute zipalign
java.lang.IllegalStateException: could not execute zipalign
	at at.favre.tools.apksigner.SignTool.execute(SignTool.java:143)
	at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:45)
	at at.favre.tools.apksigner.SignTool.main(SignTool.java:33)

Cmd history for debugging purpose:
-----------------------
[/tmp/uapksigner-5255291507018536870/linux-zipalign-29_0_24433956931453785855.tmp, -p, -v, 4, /home/user/..../apk/release/app-release-unsigned.apk, /home/user/...././app-release-unsigned-aligned.apk]
Verifying alignment of /home/user/...././app-release-unsigned-aligned.apk (4)...
      71 res/mipmap-xhdpi-v4/ic_launcher_round.png (BAD - 3)
    3796 assets/www/cordova-js-src/platform.js (OK - compressed)
    5599 AndroidManifest.xml (OK - compressed)
    6681 res/mipmap-mdpi-v4/ic_launcher_round.png (BAD - 1)
    8285 assets/www/cordova-js-src/android/nativeapiprovider.js (OK - compressed)
    9010 assets/www/cordova.js (OK - compressed)
   25953 res/mipmap-xhdpi-v4/ic_launcher.png (BAD - 1)
   27474 res/xml/config.xml (OK - compressed)
   28542 assets/www/js/about.c1c8b494.js (OK - compressed)
   29435 res/mipmap-xhdpi-v26/ic_launcher_background.png (BAD - 3)
   29621 res/mipmap-anydpi-v26/ic_launcher_round.xml (OK - compressed)
   29902 assets/www/css/app.d0415ad6.css (OK - compressed)
   30485 res/mipmap-xxhdpi-v4/ic_launcher_round.png (BAD - 1)
   36499 assets/www/js/chunk-vendors.7584f99d.js (OK - compressed)
   85570 assets/www/cordova-js-src/plugin/android/app.js (OK - compressed)
   87093 assets/www/js/app.b38801bb.js (OK - compressed)
   91230 res/mipmap-mdpi-v4/ic_launcher.png (BAD - 2)
   92012 assets/www/index.html (OK - compressed)
   92525 res/mipmap-hdpi-v26/ic_launcher_background.png (BAD - 1)
   92674 assets/www/css/about.9f825402.css (OK - compressed)
   92782 res/drawable/ic_launcher_foreground.xml (OK - compressed)
   93578 res/mipmap-mdpi-v26/ic_launcher_background.png (BAD - 2)
   93749 assets/www/cordova-js-src/android/promptbasednativeapi.js (OK - compressed)
   94574 res/mipmap-xxxhdpi-v26/ic_launcher_background.png (BAD - 2)
   94783 res/mipmap-xxhdpi-v26/ic_launcher_background.png (BAD - 3)
   94970 res/mipmap-hdpi-v4/ic_launcher.png (BAD - 2)
   96085 res/mipmap-xxxhdpi-v4/ic_launcher.png (BAD - 1)
   99683 res/mipmap-hdpi-v4/ic_launcher_round.png (BAD - 3)
  102160 resources.arsc (OK)
  105855 assets/www/cordova-js-src/exec.js (OK - compressed)
  109416 assets/www/favicon.ico (OK - compressed)
  111259 classes.dex (OK - compressed)
  160114 res/mipmap-xxxhdpi-v4/ic_launcher_round.png (BAD - 2)
  168729 assets/www/cordova_plugins.js (OK - compressed)
  168925 res/mipmap-anydpi-v26/ic_launcher.xml (OK - compressed)
  169212 res/mipmap-xxhdpi-v4/ic_launcher.png (OK)
  171713 res/mipmap-ldpi-v26/ic_launcher_background.png (BAD - 1)
Verification FAILED
 (1)
```

**Comment by patrickfav** [comment]
Which version do you use, and if it is 1.2.x could you please try 1.1.0 ?

**Comment by LeducH** [comment]
Thanks. I will do that and report.

**Comment by LeducH** [comment]
I get the same error with `1.1.0`

**Comment by LeducH** [comment]
The issue is with the icon creation of Android studio. I use it to create the icon and it misses the `res/mipmap-xhdpi-v4/ic_launcher_round.png` 

I need to open this in android studio
