### ISSUE TITLE
Error when signing

### ISSUE THREAD

**Issue by jimlyas** [patrickfav/uber-apk-signer#35]
I got this error when signing APK:
```
Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
```

**Comment by jianboy** [comment]
Me too.

```
could not verify release.apk: Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
java.lang.IllegalStateException: could not verify release.apk: Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
        at at.favre.tools.apksigner.SignTool.verifySign(SignTool.java:398)
        at at.favre.tools.apksigner.SignTool.execute(SignTool.java:119)
        at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:45)
        at at.favre.tools.apksigner.SignTool.main(SignTool.java:33)
Caused by: com.android.apksig.apk.MinSdkVersionException: Unable to determine APK's minimum supported Android platform version: malformed binary resource: AndroidManifest.xml
        at com.android.apksig.apk.ApkUtils.getMinSdkVersionFromBinaryAndroidManifest(ApkUtils.java:384)
        at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:180)
        at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:126)
        at at.favre.tools.apksigner.signing.AndroidApkSignerVerify.verify(AndroidApkSignerVerify.java:38)
        at at.favre.tools.apksigner.SignTool.verifySign(SignTool.java:334)
        ... 3 more
Caused by: com.android.apksig.internal.apk.AndroidBinXmlParser$XmlParserException: No XML chunk in file
        at com.android.apksig.internal.apk.AndroidBinXmlParser.<init>(AndroidBinXmlParser.java:101)
        at com.android.apksig.apk.ApkUtils.getMinSdkVersionFromBinaryAndroidManifest(ApkUtils.java:345)
        ... 7 more
```

**Comment by S7071** [comment]
Any luck with this?
