### ISSUE TITLE
java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.

### ISSUE THREAD

**Issue by GiorgiDolidzee** [patrickfav/uber-apk-signer#45]
This error is throwed and what can I do ?

Failed to load signer "signer #1"
java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:604)
	at java.base/sun.security.util.DerValue.init(DerValue.java:385)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:327)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:340)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1984)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:220)
	at java.base/java.security.KeyStore.load(KeyStore.java:1472)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:362)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:248)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
	at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:419)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:336)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:92)
	at at.favre.tools.apksigner.SignTool.sign(SignTool.java:314)
	at at.favre.tools.apksigner.SignTool.execute(SignTool.java:150)
	at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:45)
	at at.favre.tools.apksigner.SignTool.main(SignTool.java:33)

**Comment by SmartManoj** [comment]
https://github.com/r0adkll/sign-android-release/issues/34
